In [1]:
!ls

Untitled.ipynb                countries.csv.zip
X_air.csv                     sample_submission_NDF.csv
age_gender_bkts.csv           sample_submission_NDF.csv.zip
age_gender_bkts.csv.zip       sessions.csv
air.py                        sessions.csv.zip
airbnb_data.csv               test_users.csv
airbnb_eda.ipynb              test_users.csv.zip
airbnb_home.ipynb             train_users_2.csv
airbnb_model.ipynb            train_users_2.csv.zip
countries.csv                 y)air.csv

In [13]:
data = pd.read_csv('./airbnb_data.csv')

In [14]:
data

,id,age,signup_flow,country_destination,date_account_created_01,date_account_created_02,date_account_created_03,date_account_created_04,date_account_created_05,date_account_created_06,...,affiliate_provider_yahoo,affiliate_provider_yandex,first_affiliate_tracked_linked,first_affiliate_tracked_local ops,first_affiliate_tracked_marketing,first_affiliate_tracked_omg,first_affiliate_tracked_product,first_affiliate_tracked_tracked-other,first_affiliate_tracked_untracked,target
0,gxn3p5htnn,34.0,0,NDF,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,7
1,820tgsjxq7,38.0,0,NDF,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,7
2,4ft3gnwmtx,56.0,3,US,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,10
3,bjjt8pjhuk,42.0,0,other,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,11
4,87mebub9p4,41.0,0,US,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213446,zxodksqpep,32.0,0,NDF,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,7
213447,mhewnxesx9,34.0,0,NDF,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,7
213448,6o3arsjbb4,32.0,0,NDF,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,7
213449,jh95kwisub,34.0,25,NDF,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,7
213450,nw9fwlyb5f,34.0,25,NDF,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,7

In [15]:
data['target']

0          7
1          7
2         10
3         11
4         10
          ..
213446     7
213447     7
213448     7
213449     7
213450     7
Name: target, Length: 213451, dtype: int64

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
onehot = OneHotEncoder()

In [18]:
target_onehot = onehot.fit_transform(data[['target']])

In [20]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

mm = MinMaxScaler()
ss = StandardScaler()
rs = RobustScaler()

X = data.drop(['id', 'country_destination', 'target'], axis=1)
y = target_onehot.toarray()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=13, shuffle=True)

ss_f = ss.fit(X_train)
X_train = ss_f.transform(X_train)
X_test = ss_f.transform(X_test)

In [22]:
print(X_train.shape, y_train.shape)

(170760, 75) (170760, 12)

In [23]:
model = keras.Sequential([

layers.Dense(32, activation='relu', input_shape=[75]),  

layers.Dense(16, activation='relu'),
    
layers.Dense(12, activation='softmax')
])

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

model.compile(loss='categorical_crossentropy',
                optimizer=optimizer, metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 32)                2432
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528
_________________________________________________________________
dense_2 (Dense)              (None, 12)                204
=================================================================
Total params: 3,164
Trainable params: 3,164
Non-trainable params: 0
_________________________________________________________________

In [1]:
history = model.fit(X_train, y_train, batch_size=16, epochs=100 , verbose=1, validation_data=(X_test, y_test))

In [118]:
model.predict_proba(X_train[[0]])

array([[3.4014575e-04, 2.7711999e-03, 2.0159986e-03, 1.1962445e-02,
        2.7479520e-02, 8.3801793e-03, 2.2490732e-02, 5.7274413e-01,
        2.5312381e-03, 7.6129079e-05, 3.1249687e-01, 3.6711298e-02]],
      dtype=float32)